apiVersion: apps/v1

kind: ReplicaSet
metadata:
  name: express-mbouranga-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express-container
        image: winnmbg/back_kube:latest
        ports:
        - containerPort: 3001
      - name: mysql-container
        image: winnmbg/back_kube:latest
        ports:
        - containerPort: 3001

kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
  containers:
  - name: mysql
    image: mysql:5.7
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    volumeMounts:
    - name: mysql-persistent-storage
      mountPath: /var/lib/mysql

kind: Service
metadata:
  name: express-mbouranga-service
spec:
  selector:
    app: express-mbouranga-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
  externalIPs:
    - "10.152.183.232"
