apiVersion: v1

kind: ReplicaSet
metadata:
  name: express-mbouranga-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express-container
        image: winnmbg/back_kube:0.2
        ports:
        - containerPort: 3001

kind: Service
metadata:
  name: express-mbouranga-service
spec:
  selector:
    app: express-mbouranga-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
