apiVersion: v1
kind: Pod
metadata:
  name: simple-pod-mbouranga
spec:
  containers:
  - name: backend-mbouranga-container
    image: winnmbg/back_kube:latest
    ports:
    - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: simple-service-mbouranga
spec:
  selector:
    app: simple-pod-mbouranga
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
