apiVersion: apps/v1

kind: Deployment
metadata:
  name: winn-express-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: winn-express-front
  template:
    metadata:
      labels:
        app: winn-express-front
    spec:
      containers:
      - name: winn-express-front
        image: winnmbg/front_kube:0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "256Mi"



apiVersion: v1
kind: Service
metadata:
  name: winn-express-front
spec:
  selector:
    app: winn-express-front
  ports:
    - protocol: TCP
      port: 802
      targetPort: 3000
  type: LoadBalancer