name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
          
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_LOGIN }}/back_kube:0.3 .
      
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_LOGIN }}/back_kube:0.3
  
      - name: Install kubectl
        run: sudo apt-get update && sudo snap install kubectl --classic

      - name: Install Azure CLI
        run: sudo apt-get -y update && sudo apt-get -y install azure-cli && az
      
      - name: Connect Azure Cloud
        run: az login --service-principal -u ${{ secrets.APPID }} -p ${{ secrets.AZ_SECRET }} --tenant ${{ secrets.TENANT_ID }}

      - name: Get Azure kubernetes cluster informations
        run: az aks get-credentials --resource-group hitema_kube --name hitema

      - name: Update Kubernetes cluster
        run: kubectl apply -f replicas.yaml && kubectl apply -f mysql.yaml

